// Auto-generated by common/schemas/codegen.sh — do not edit manually.
#![allow(dead_code, clippy::all)]

pub mod backtest_config;
pub mod backtest_result;
pub mod factor;
pub mod ohlcv;
pub mod signal;
pub mod symbol;
