# generated by datamodel-codegen:
#   filename:  backtest_config.schema.json

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, confloat


class FillModel(StrEnum):
    """
    How the simulator fills orders
    """

    next_open = 'next_open'
    next_close = 'next_close'
    vwap = 'vwap'


class DataFrequency(StrEnum):
    """
    Bar frequency
    """

    field_1m = '1m'
    field_5m = '5m'
    field_15m = '15m'
    field_30m = '30m'
    field_1h = '1h'
    field_1d = '1d'


class BacktestConfig(BaseModel):
    """
    Configuration for a backtest run.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    strategy_id: str
    """
    Strategy identifier (Rhai script name or native trait id)
    """
    strategy_params: dict[str, Any] | None = None
    """
    Strategy-specific parameter object; schema strategy-defined
    """
    universe: list[str] = Field(..., min_length=1)
    """
    List of symbols traded in the backtest
    """
    start_date: date
    """
    Inclusive start date (ISO 8601 date)
    """
    end_date: date
    """
    Inclusive end date (ISO 8601 date)
    """
    initial_capital: confloat(ge=0.0)
    """
    Starting cash
    """
    fee_rate: confloat(ge=0.0) | None = None
    """
    Per-trade fee rate (fraction, e.g. 0.001 = 10 bps)
    """
    slippage_bps: confloat(ge=0.0) | None = None
    """
    Assumed slippage in basis points
    """
    fill_model: FillModel | None = None
    """
    How the simulator fills orders
    """
    data_frequency: DataFrequency | None = None
    """
    Bar frequency
    """
