# generated by datamodel-codegen:
#   filename:  factor.schema.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict


class FactorValue(BaseModel):
    """
    Single computed factor value at a point in time.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    factor_id: str
    """
    Factor identifier, e.g. 'sma_20', 'rsi_14'
    """
    symbol: str
    timestamp: AwareDatetime
    value: float
    """
    Computed factor value (NaN encoded as JSON null)
    """
    version: str | None = None
    """
    Factor implementation version, optional
    """
