# generated by datamodel-codegen:
#   filename:  ohlcv.schema.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Ohlcv(BaseModel):
    """
    OHLCV bar data point. One row per (symbol, timestamp).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    symbol: str
    """
    Asset symbol identifier
    """
    timestamp: AwareDatetime
    """
    ISO 8601 UTC timestamp at the bar start
    """
    open: float
    """
    Opening price
    """
    high: float
    """
    Highest price during the bar
    """
    low: float
    """
    Lowest price during the bar
    """
    close: float
    """
    Closing price
    """
    volume: float
    """
    Volume traded during the bar
    """
    adjusted: bool | None = None
    """
    Whether prices are adjusted for splits/dividends
    """
