# generated by datamodel-codegen:
#   filename:  signal.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat


class Action(StrEnum):
    """
    Direction the strategy proposes
    """

    long = 'long'
    short = 'short'
    flat = 'flat'
    hold = 'hold'


class Signal(BaseModel):
    """
    Strategy-generated trading signal.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    signal_id: str
    """
    Unique signal identifier (UUID or deterministic hash)
    """
    symbol: str
    timestamp: AwareDatetime
    action: Action
    """
    Direction the strategy proposes
    """
    strength: confloat(ge=0.0, le=1.0) | None = None
    """
    Confidence/sizing weight in [0, 1]
    """
    source: str | None = None
    """
    Strategy id or model id that produced this signal
    """
    reason: str | None = None
    """
    Human-readable explanation, optional
    """
