# generated by datamodel-codegen:
#   filename:  symbol.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, confloat


class Exchange(StrEnum):
    """
    Listing/trading venue
    """

    NYSE = 'NYSE'
    NASDAQ = 'NASDAQ'
    ARCA = 'ARCA'
    HKEX = 'HKEX'
    SSE = 'SSE'
    SZSE = 'SZSE'
    OKX = 'OKX'
    OPRA = 'OPRA'


class AssetClass(StrEnum):
    """
    Asset class taxonomy
    """

    stock = 'stock'
    etf = 'etf'
    option = 'option'
    index = 'index'
    crypto_spot = 'crypto_spot'
    crypto_perp = 'crypto_perp'
    crypto_futures = 'crypto_futures'


class Symbol(BaseModel):
    """
    Trading instrument metadata.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    symbol: str
    """
    Asset symbol identifier
    """
    exchange: Exchange
    """
    Listing/trading venue
    """
    asset_class: AssetClass
    """
    Asset class taxonomy
    """
    currency: str
    """
    Quote currency ISO 4217 code (or asset code for crypto)
    """
    tick_size: confloat(ge=0.0) | None = None
    """
    Minimum price increment
    """
    lot_size: confloat(ge=0.0) | None = None
    """
    Minimum quantity increment
    """
