#!/usr/bin/env bash
# Cross-language type generator from common/schemas/*.schema.json
#
# Outputs:
#   - common/python/quantpilot_common/schemas/*.py        (Pydantic v2)
#   - apps/quant-assistant/backend/src/schemas/*.rs       (serde structs)
#   - common/frontend-components/src/types/*.ts           (TS interfaces)
#
# Idempotent: re-run produces identical output (CI uses this for drift check).

set -euo pipefail

# Resolve repo root regardless of caller's cwd
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

SCHEMA_DIR="common/schemas"
PY_OUT="common/python/quantpilot_common/schemas"
RUST_OUT="apps/quant-assistant/backend/src/schemas"
TS_OUT="common/frontend-components/src/types"

mkdir -p "$PY_OUT" "$RUST_OUT" "$TS_OUT"

# Tool dispatch
have_uv=$(command -v uv || true)
have_npx=$(command -v npx || true)
if [[ -z "$have_uv" ]]; then
  echo "ERROR: 'uv' not found in PATH; install via 'brew install uv'" >&2
  exit 1
fi
if [[ -z "$have_npx" ]]; then
  echo "ERROR: 'npx' not found in PATH; install Node.js" >&2
  exit 1
fi

# Iterate schemas in deterministic (sorted) order
schemas=()
while IFS= read -r f; do
  schemas+=("$f")
done < <(find "$SCHEMA_DIR" -maxdepth 1 -name "*.schema.json" | sort)

if [[ ${#schemas[@]} -eq 0 ]]; then
  echo "ERROR: no schemas found in $SCHEMA_DIR" >&2
  exit 1
fi

echo "== Codegen for ${#schemas[@]} schemas =="

# Per-schema generation
for schema_path in "${schemas[@]}"; do
  base=$(basename "$schema_path" .schema.json)

  # Python: datamodel-codegen → Pydantic v2
  uv run --with 'datamodel-code-generator>=0.25.0' \
    datamodel-codegen \
      --input "$schema_path" \
      --input-file-type jsonschema \
      --output "$PY_OUT/${base}.py" \
      --output-model-type pydantic_v2.BaseModel \
      --target-python-version 3.12 \
      --use-schema-description \
      --use-field-description \
      --disable-timestamp

  # Rust: quicktype → serde structs
  npx --yes quicktype \
    --src "$schema_path" \
    --src-lang schema \
    --lang rust \
    --top-level "$(echo "$base" | python3 -c 'import sys; print("".join(p.capitalize() for p in sys.stdin.read().strip().split("_")))')" \
    --visibility public \
    --derive-debug \
    --derive-clone \
    --derive-partial-eq \
    --out "$RUST_OUT/${base}.rs"

  # TypeScript: quicktype
  npx --yes quicktype \
    --src "$schema_path" \
    --src-lang schema \
    --lang typescript \
    --top-level "$(echo "$base" | python3 -c 'import sys; print("".join(p.capitalize() for p in sys.stdin.read().strip().split("_")))')" \
    --just-types \
    --no-runtime-typecheck \
    --out "$TS_OUT/${base}.ts"

  echo "  ✓ $base"
done

# Generate Python schemas/__init__.py with re-exports
{
  echo "\"\"\"Auto-generated by common/schemas/codegen.sh — do not edit manually.\"\"\""
  echo
  for schema_path in "${schemas[@]}"; do
    base=$(basename "$schema_path" .schema.json)
    echo "from quantpilot_common.schemas.${base} import *  # noqa: F401, F403"
  done
} > "$PY_OUT/__init__.py"

# Generate Rust mod.rs aggregating modules
{
  echo "// Auto-generated by common/schemas/codegen.sh — do not edit manually."
  echo "#![allow(dead_code, clippy::all)]"
  echo
  for schema_path in "${schemas[@]}"; do
    base=$(basename "$schema_path" .schema.json)
    echo "pub mod ${base};"
  done
} > "$RUST_OUT/mod.rs"

# Generate TS index.ts
{
  echo "// Auto-generated by common/schemas/codegen.sh — do not edit manually."
  for schema_path in "${schemas[@]}"; do
    base=$(basename "$schema_path" .schema.json)
    echo "export * from './${base}';"
  done
} > "$TS_OUT/index.ts"

echo "== Codegen complete =="
echo "  Python: $PY_OUT/"
echo "  Rust:   $RUST_OUT/"
echo "  TS:     $TS_OUT/"
